name: build

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.9.0"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam run -m build
      - name: Install npm dependencies
        run: |
          sudo apt-get install -y npm
          npm install
      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./static/main.css -o ./priv/style.css
      - name: Upload priv directory
        uses: actions/upload-artifact@v4
        with:
          name: priv
          path: priv/